version: '3'
services:
  app:
    image: readyx-api
    ports:
      - "8080:8080"
#    depends_on:
#      - db
#  db:
#    image: mysql:8
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpassword
#      MYSQL_DATABASE: your_database_name
#      MYSQL_USER: your_username
#      MYSQL_PASSWORD: your_password
#    ports:
#      - "3306:3306"
