version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8081:8080"
    networks:
      - app-network
    restart: unless-stopped  # 충돌 방지용 설정

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    ports:
      - "8082:8080"
    networks:
      - app-network
    restart: unless-stopped  # 충돌 방지용 설정

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - app
      - app2
    restart: unless-stopped  # 충돌 방지용 설정

networks:
  app-network:
    driver: bridge
